GET http://localhost:3001/api/notes

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "blablablabla",
    "important": true
}

###

DELETE http://localhost:3001/api/notes/635a64ac806e3b6ffedb825e
